# 1. Numpy
- Numpy = Numerical Python
- main object -> ndarray

In [2]:
pip install numpy

Requirement already satisfied: numpy in c:\users\user\anaconda\lib\site-packages (1.26.4)
Note: you may need to restart the kernel to use updated packages.

## 1.1. ndarray
- N-dimensional array.
- collection of elments of the same datatype.
- each element is stored as a data-type(dtype) object

## 1.2. Creating an array

In [8]:
import numpy as np

# 1-D array
my_list = [10, 20, 30]
print(type(np.array(my_list)))
np.array(my_list)

<class 'numpy.ndarray'>

array([10, 20, 30])

In [10]:
# 2-D array
list_of_lists = [[10,20,30],[12, 23, 34],[45, 23, 89]]
np.array(list_of_lists)

array([[10, 20, 30],
       [12, 23, 34],
       [45, 23, 89]])

## 1.3 Attributes of ndarray object
- ndarray.shape -> dimension **(n, m)**
      - len of shape tuple give the no. of dimension, **ndim**
- ndarray.dtype -> type of elements in array
- ndarray.reshape -> row to column and vice versa

In [19]:
num_list = [10, 20, 30, 40]

num_array = np.array(num_list)

print(num_array.dtype)
print(num_array.shape)
print(num_array.reshape(2, 2))

int32
(4,)
[[10 20]
 [30 40]]

## 1.4 Built-in Methods
- **arange** -> same as range
- **zeros** and **ones**
- **linspace**

In [42]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.zeros((1,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [66]:
np.ones((2,4,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [68]:
np.linspace(0,10,5) # five equally spaced nos in range 10

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## 1.5 Generating Random Numbers
- **rand** - uniform distribution
- **randn** - normal distribution
- **randint** - specified no of random int within a given range

In [81]:
np.random.rand(2,4) # 2,4 is the shape of the generated array

array([[0.35277071, 0.09811857, 0.9661308 , 0.66726617],
       [0.33251479, 0.32149525, 0.91524948, 0.12515351]])

In [83]:
np.random.randn(2,4) # 2,4 is the shape of the array

array([[ 0.84479557, -1.07409033, -0.89786814, -1.70912125],
       [ 1.18247182, -1.33711483,  0.84891145,  0.88577401]])

In [87]:
np.random.randint(1,4,3) # Generates array of 3 random nos btw 1 and 4

array([2, 2, 3])

---
# 2. Pandas
- Major data structures in Pandas:
  - Series
  - Dataframe
  - Panel
  - Panel 4D

## 2.1. Series
- similar to ndarray but has axis labels, i.e., it can be indexed using labels not just numbers.

### 2.1.1. Creating a Series
- list, ndarray, and dict can be converted to Series.
- pandas.Series()

In [30]:
import pandas as pd

# Creating Series from list

my_list = [10, 20, 30]
series = pd.Series(my_list)
print(series)

0    10
1    20
2    30
dtype: int64

In [32]:
# Creating series from NumPy array 

ind = ['a', 'b', 'c']
arr = np.array([10, 20, 30])

pd.Series(data = arr, index = ind)

a    10
b    20
c    30
dtype: int32

In [34]:
# Creating a Series from a dictionary

my_dict = {'a':10, 'b':20, 'c':30}

pd.Series(my_dict)

a    10
b    20
c    30
dtype: int64

### 2.1.2. Series Attributes
- Series.index
- Series.values

In [24]:
print(series.index)
print(series.values)

RangeIndex(start=0, stop=3, step=1)
[10 20 30]

In [26]:
type(series.values)

numpy.ndarray

In [28]:
type(series.index)

pandas.core.indexes.range.RangeIndex

### 2.1.3. Using index in Series

In [47]:
ser1 = pd.Series([1,2,3,4], index = ['USA', 'Japan', 'Germany', 'USSR'])
ser2 = pd.Series([1,2,3,4], index = ['USA', 'Japan', 'Italy', 'Germany'])

print(ser1)

USA        1
Japan      2
Germany    3
USSR       4
dtype: int64

In [49]:
ser1 + ser2

Germany    7.0
Italy      NaN
Japan      4.0
USA        2.0
USSR       NaN
dtype: float64

In [51]:
ser1['USA']

1

## 2.2 DataFrame
- 2D grid
- row = instance
- col = values of one variable
### 2.2.1 Creating a dataframe

In [57]:
df = pd.DataFrame([[1, 2, 3],
                   [3, 4, 5],
                   [5, 6, 7]])
df

   0  1  2
0  1  2  3
1  3  4  5
2  5  6  7

In [61]:
print(df.shape)
print(df.index)

(3, 3)
RangeIndex(start=0, stop=3, step=1)

### 2.2.2. Understanding the index

In [66]:
df = pd.DataFrame([[1, 2, 3], 
                  [3, 4, 5],
                  [5, 6, 7]],
                 index = ['a', 'b', 'c'],
                 columns = ['x', 'y', 'z'])
print(df)
print(df.shape)
print(df.index)
print(df.columns)

   x  y  z
a  1  2  3
b  3  4  5
c  5  6  7
(3, 3)
Index(['a', 'b', 'c'], dtype='object')
Index(['x', 'y', 'z'], dtype='object')

In [87]:
df['x']['a']

1

### 2.2.3. The Weather Dataset: Reading DataFrames from files

In [66]:
import pandas as pd

# Read the weather data into a DataFrame
weather_df = pd.read_csv('weather_2012.csv')

print(weather_df.shape)
print(weather_df.index)
print(list(weather_df.columns))

(8784, 8)
RangeIndex(start=0, stop=8784, step=1)
['Date/Time', 'Temp (C)', 'Dew Point Temp (C)', 'Rel Hum (%)', 'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Weather']

weather_df['Date/Time'].head()

In [69]:
weather_df['Date/Time'] =  pd.to_datetime(weather_df['Date/Time']) # weather_df doesn't change if assignment is not done
weather_df['Date/Time'].head()

0   2012-01-01 00:00:00
1   2012-01-01 01:00:00
2   2012-01-01 02:00:00
3   2012-01-01 03:00:00
4   2012-01-01 04:00:00
Name: Date/Time, dtype: datetime64[ns]

### 2.2.4. How to Analyze DataFrames
- `info()`

In [138]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date/Time           5 non-null      datetime64[ns]
 1   Temp (C)            8784 non-null   float64
 2   Dew Point Temp (C)  8784 non-null   float64
 3   Rel Hum (%)         8784 non-null   int64
 4   Wind Spd (km/h)     8784 non-null   int64
 5   Visibility (km)     8784 non-null   float64
 6   Stn Press (kPa)     8784 non-null   float64
 7   Weather             8784 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB

- `head()`

In [121]:
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

- `tail()`

In [124]:
weather_df.tail()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

- `.index`

In [147]:
weather_df.index

RangeIndex(start=0, stop=8784, step=1)

- `.unique()`

In [152]:
weather_df['Weather'].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 'Rain,Snow Grains', 'Rain,Snow,Ice Pellets',
       'Snow Showers,Fog', 'Moderate Snow,Blowing Snow'], dtype=object)

In [158]:
print(weather_df['Wind Spd (km/h)'].unique())

[ 4  7  6  9 15 13 20 22 19 24 30 35 39 32 33 26 44 43 48 37 28 17 11  0
 83 70 57 46 41 52 50 63 54  2]

- `.nunique()`

In [154]:
weather_df['Weather'].nunique()

50

- `.value_counts`

In [163]:
weather_df['Weather'].value_counts()

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Freezing Fog                                  4
Snow Showers,Fog                              4
Moderate Snow                                 4
Rain,Snow,Ice Pellets                         4
Freezing Rain,Fog                             4
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Rain,Haze                            2
Drizzle,Snow                                  2
Rain Showers,Snow Showers                     2
Thunderstorms                                 2
Moderate Snow,Blowing Snow                    2
Rain Showers,Fog                              1
Thunderstorms,Moderate Rain Showers,Fog       1
Snow Pellets                                  1
Rain,Snow,Fog                                 1
Moderate Rain,Fog                             1
Freezing Rain,Ice Pellets,Fog                 1
Drizzle,Ice Pellets,Fog                       1
Thunderstorms,Rain,Fog                        1
Rain,Ice Pellets                              1
Rain,Snow Grains                              1
Thunderstorms,Heavy Rain Showers              1
Freezing Rain,Snow Grains                     1
Name: count, dtype: int64

In [172]:
# No of times weather is clear

weather_df['Weather'].value_counts()[3]

C:\Users\user\AppData\Local\Temp\ipykernel_8408\89708427.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  weather_df['Weather'].value_counts()[3]

1326

In [178]:
# No of times wind speed was 4 km/h
weather_df['Wind Spd (km/h)'].value_counts()[9]

830

### 2.2.5 Data Manipulation - Gets you desired results

### 2.2.5.1 Selection (Part 1)

#### **How to get the weather column from the "weather_df" dataframe?**

In [12]:
weather = weather_df['Weather']

print(type(weather))
weather.head()

<class 'pandas.core.series.Series'>

0                     Fog
1                     Fog
2    Freezing Drizzle,Fog
3    Freezing Drizzle,Fog
4                     Fog
Name: Weather, dtype: object

#### **How to get the weather and temperature columns from the "weather_df" dataframe?**

In [3]:
two_cols = weather_df[['Weather', 'Temp (C)']]

print(type(two_cols))
two_cols.head()

<class 'pandas.core.frame.DataFrame'>

                Weather  Temp (C)
0                   Fog      -1.8
1                   Fog      -1.8
2  Freezing Drizzle,Fog      -1.8
3  Freezing Drizzle,Fog      -1.5
4                   Fog      -1.5

#### **Get the first 25 rows from the "weather_df" dataframe**

In [29]:
weather_df[:25]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
7,2012-01-01 07:00:00,-1.4,-3.6,85,7,8.0,101.26,Fog
8,2012-01-01 08:00:00,-1.4,-3.6,85,9,8.0,101.23,Fog
9,2012-01-01 09:00:00,-1.3,-3.1,88,15,4.0,101.20,Fog
10,2012-01-01 10:00:00,-1.0,-2.3,91,9,1.2,101.15,Fog
11,2012-01-01 11:00:00,-0.5,-2.1,89,7,4.0,100.98,Fog
12,2012-01-01 12:00:00,-0.2,-2.0,88,9,4.8,100.79,Fog
13,2012-01-01 13:00:00,0.2,-1.7,87,13,4.8,100.58,Fog
14,2012-01-01 14:00:00,0.8,-1.1,87,20,4.8,100.31,Fog
15,2012-01-01 15:00:00,1.8,-0.4,85,22,6.4,100.07,Fog
16,2012-01-01 16:00:00,2.6,-0.2,82,13,12.9,99.93,Mostly Cloudy
17,2012-01-01 17:00:00,3.0,0.0,81,13,16.1,99.81,Cloudy
18,2012-01-01 18:00:00,3.8,1.0,82,15,12.9,99.74,Rain
19,2012-01-01 19:00:00,3.1,1.3,88,15,12.9,99.68,Rain
20,2012-01-01 20:00:00,3.2,1.3,87,19,25.0,99.50,Cloudy
21,2012-01-01 21:00:00,4.0,1.7,85,20,25.0,99.39,Cloudy
22,2012-01-01 22:00:00,4.4,1.9,84,24,19.3,99.32,Rain Showers
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers

#### **Get 3 alternating rows, but only Visibility and Relative Humidity columns.**

In [5]:
# solution 1
result_1 = weather_df[['Visibility (km)', 'Rel Hum (%)']][:5:2]

# solution_2
result_2 = weather_df[:5:2][['Visibility (km)', 'Rel Hum (%)']]

print(result_1)
result_1 == result_2

   Visibility (km)  Rel Hum (%)
0              8.0           86
2              4.0           89
4              4.8           88

   Visibility (km)  Rel Hum (%)
0             True         True
2             True         True
4             True         True

#### **Do not use slicing**
- Chained indexing may give unpredictable behaviours when writing to a DataFrame.
- Because indexing either returns a 'view' or 'copy' of the DataFrame.
  
---

### 2.2.5.2. Selection (Part 2)

- `.loc`

In [58]:
weather_df.loc[0:5, ['Visibility (km)', 'Rel Hum (%)']]

   Visibility (km)  Rel Hum (%)
0              8.0           86
1              8.0           87
2              4.0           89
3              4.0           88
4              4.8           88
5              6.4           87

- `.iloc`

In [60]:
weather_df[['Visibility (km)', 'Rel Hum (%)']].iloc[0:5]

   Visibility (km)  Rel Hum (%)
0              8.0           86
1              8.0           87
2              4.0           89
3              4.0           88
4              4.8           88

### Mini Challenge 
Get 3 alternate rows

In [66]:
weather_df.loc[0:5:2, ['Visibility (km)', 'Rel Hum (%)']]

   Visibility (km)  Rel Hum (%)
0              8.0           86
2              4.0           89
4              4.8           88

---

### 2.2.5.3 Filtering

#### **Find all instances when snow was recorded.**

In [121]:
snow_filter = weather_df['Weather'] == 'Snow'
weather_df[snow_filter]

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
55,2012-01-03 07:00:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,2012-01-04 12:00:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,2012-01-04 14:00:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,2012-01-04 15:00:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,2012-01-04 16:00:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [111]:
snow_filter = weather_df['Weather'].str.lower().str.contains('snow')

print(snow_filter)
weather_df[snow_filter]

0       False
1       False
2       False
3       False
4       False
        ...
8779     True
8780     True
8781     True
8782     True
8783     True
Name: Weather, Length: 8784, dtype: bool

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
41,2012-01-02 17:00:00,-2.1,-9.5,57,22,25.0,99.66,Snow Showers
44,2012-01-02 20:00:00,-5.6,-13.4,54,24,25.0,100.07,Snow Showers
45,2012-01-02 21:00:00,-5.8,-12.8,58,26,25.0,100.15,Snow Showers
47,2012-01-02 23:00:00,-7.4,-14.1,59,17,19.3,100.27,Snow Showers
48,2012-01-03 00:00:00,-9.0,-16.0,57,28,25.0,100.35,Snow Showers
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

#### **Find all instances were visibility was 25 and wind speed was above 24.**

In [153]:
df = weather_df[(weather_df['Visibility (km)'] == 25) & (weather_df['Wind Spd (km/h)'] > 24)]

df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy

---
### 2.2.5.4 Series Operations

In [27]:
weather_df['Wind Spd (km/h)'].head() + 10

0    14
1    14
2    17
3    16
4    17
Name: Wind Spd (km/h), dtype: int64

In [14]:
weather_df['Wind Spd (km/h)'].head() /2

0    2.0
1    2.0
2    3.5
3    3.0
4    3.5
Name: Wind Spd (km/h), dtype: float64

In [24]:
weather_df['new col'] = weather_df['Temp (C)'] + weather_df['Dew Point Temp (C)']
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new col
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8

### Apply / Call Functions

- `.apply()`

In [41]:
def times2(value):
    return value * 2

weather_df['Wind Spd (km/h)'].apply(times2).head()

0     8
1     8
2    14
3    12
4    14
Name: Wind Spd (km/h), dtype: int64

- `.describe()`

In [44]:
weather_df.describe()

,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),new col
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623,11.353438
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005,22.188521
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000,-51.800000
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000,-5.300000
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000,12.200000
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000,30.600000
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000,53.400000

### Adding / Updating Columns

In [65]:
# Always do this in two steps
weather_vis_metre = weather_df['Visibility (km)'] * 1000
weather_df['Visibility (metres)'] = weather_vis_metre

weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new col,Visibility (m),Visibility (metres)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0,4800.0

### Renaming Columns
### **`.rename()`**

In [82]:
weather_df.rename(columns = {'Visibility (metres)' : 'Visibility (m)'}, inplace = True)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather,new col,Visibility (m)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog,-5.7,8000.0
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog,-5.5,8000.0
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog",-5.2,4000.0
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog",-4.7,4000.0
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog,-4.8,4800.0

### Deleting Columns
###  **`.drop()`**

In [80]:
weather_df = weather_df.drop(labels = ['Weather'], axis = 1)
weather_df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23

### Sorting Values
### **`.sort_values()`**

In [103]:
weather_df.sort_values('Temp (C)', ascending = False).head(10)   # can be inplace as well

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
4695,2012-07-14 15:00:00,33.0,16.8,38,22,48.3,101.31,Mainly Clear
4143,2012-06-21 15:00:00,33.0,19.0,44,24,24.1,100.20,Mainly Clear
4696,2012-07-14 16:00:00,32.9,15.3,35,24,48.3,101.26,Mainly Clear
5199,2012-08-04 15:00:00,32.8,18.8,44,17,24.1,101.39,Clear
4694,2012-07-14 14:00:00,32.7,15.3,35,28,48.3,101.35,Mainly Clear
4142,2012-06-21 14:00:00,32.6,20.4,49,20,24.1,100.25,Mainly Clear
5201,2012-08-04 17:00:00,32.5,19.8,47,13,24.1,101.32,Clear
5200,2012-08-04 16:00:00,32.5,18.5,44,15,24.1,101.34,Clear
4697,2012-07-14 17:00:00,32.5,16.5,38,19,48.3,101.22,Mainly Clear
4144,2012-06-21 16:00:00,32.5,17.9,42,24,24.1,100.14,Mainly Clear

### Summarize  
### **`.pivot_table()`**

In [8]:
data = {
    'A': ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'],
    'B': ['one', 'one','two', 'two', 'one', 'one'],
    'C': ['x', 'y', 'x', 'y', 'x', 'y'],
    'D': [1, 3, 2, 5, 4, 1]
}

df = pd.DataFrame(data)
df

     A    B  C  D
0  foo  one  x  1
1  foo  one  y  3
2  foo  two  x  2
3  bar  two  y  5
4  bar  one  x  4
5  bar  one  y  1

In [71]:
import numpy as np

sum = df.pivot_table(
    values = 'D',
    index = 'A',
    columns = ['C'],
    aggfunc = np.sum)
sum

C:\Users\user\AppData\Local\Temp\ipykernel_1688\2851981549.py:3: FutureWarning: The provided callable <function sum at 0x000001AE037CAFC0> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  sum = df.pivot_table(

C    x  y
A
bar  4  6
foo  3  3

### **`.reset_index()`**

In [73]:
sum.reset_index()

C    A  x  y
0  bar  4  6
1  foo  3  3

### **What is the mean temp recorded by month?**

In [75]:
mean_temp = weather_df.pivot_table(
    values = 'Temp (C)',
    index = weather_df['Date/Time'].dt.month,
    aggfunc = np.mean
)

mean_temp.reset_index().head()

C:\Users\user\AppData\Local\Temp\ipykernel_1688\3677597372.py:1: FutureWarning: The provided callable <function mean at 0x000001AE037E00E0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  mean_temp = weather_df.pivot_table(

   Date/Time   Temp (C)
0          1  -7.371505
1          2  -4.225000
2          3   3.121237
3          4   7.009306
4          5  16.237769

### **`.groupby()`**

In [82]:
weather_df.groupby(weather_df['Date/Time'].dt.month).agg(np.mean)

C:\Users\user\AppData\Local\Temp\ipykernel_1688\3577844264.py:1: FutureWarning: The provided callable <function mean at 0x000001AE037E00E0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  weather_df.groupby(weather_df['Date/Time'].dt.month).agg(np.mean)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa)
Date/Time,,,,,,,
1,2012-01-16 11:30:00,-7.371505,-12.294758,68.383065,18.108871,22.100269,101.005349
2,2012-02-15 11:30:00,-4.225000,-9.221695,68.956897,14.837644,25.182184,101.142414
3,2012-03-16 11:30:00,3.121237,-3.488575,64.862903,14.514785,26.177957,101.335255
4,2012-04-15 23:30:00,7.009306,-1.934583,56.150000,17.369444,31.777083,100.716833
5,2012-05-16 11:30:00,16.237769,8.080780,61.760753,12.846774,29.418548,101.057164
6,2012-06-15 23:30:00,20.134028,11.738056,60.643056,14.681944,32.104167,100.784222
7,2012-07-16 11:30:00,22.790054,14.595430,62.017473,11.887097,33.655108,100.828333
8,2012-08-16 11:30:00,22.279301,15.644758,67.943548,13.931452,30.192608,100.927097
9,2012-09-15 23:30:00,16.484444,10.757917,71.165278,14.108333,30.603472,101.087903
10,2012-10-16 11:30:00,10.954973,6.533468,75.731183,15.475806,25.111022,100.909368
11,2012-11-15 23:30:00,0.931389,-4.179306,69.984722,13.973611,26.077083,101.658306
12,2012-12-16 11:30:00,-3.306317,-6.129032,81.299731,17.614247,19.733199,101.174409

In [88]:
weather_df.groupby(weather_df['Date/Time'].dt.month).agg(np.mean)['Temp (C)'].reset_index()

C:\Users\user\AppData\Local\Temp\ipykernel_1688\1270209855.py:1: FutureWarning: The provided callable <function mean at 0x000001AE037E00E0> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  weather_df.groupby(weather_df['Date/Time'].dt.month).agg(np.mean)['Temp (C)'].reset_index()

    Date/Time   Temp (C)
0           1  -7.371505
1           2  -4.225000
2           3   3.121237
3           4   7.009306
4           5  16.237769
5           6  20.134028
6           7  22.790054
7           8  22.279301
8           9  16.484444
9          10  10.954973
10         11   0.931389
11         12  -3.306317

### Concat, Merge, and Join
### **`pd.concat([dataframes], axis = 0)`**

In [91]:
df1 = pd.DataFrame(
    {
        'A': [0, 1, 2, 3],
        'B': [4, 5, 6, 7],
        'C': [8, 9, 10, 11]
    }, index = [0, 1, 2, 3]
)

df2 = pd.DataFrame(
    {
        'A': [0, 1, 2, 3],
        'B': [4, 5, 6, 7],
        'C': [8, 9, 10, 11]
    }, index = [4, 5, 6, 7]
)

df3 = pd.DataFrame(
    {
        'A': [0, 1, 2, 3],
        'B': [4, 5, 6, 7],
        'C': [8, 9, 10, 11]
    }, index = [8, 9, 10, 11]
)

In [93]:
df1

   A  B   C
0  0  4   8
1  1  5   9
2  2  6  10
3  3  7  11

In [95]:
df2

   A  B   C
4  0  4   8
5  1  5   9
6  2  6  10
7  3  7  11

In [97]:
df3

    A  B   C
8   0  4   8
9   1  5   9
10  2  6  10
11  3  7  11

In [109]:
pd.concat([df1, df2, df3])

    A  B   C
0   0  4   8
1   1  5   9
2   2  6  10
3   3  7  11
4   0  4   8
5   1  5   9
6   2  6  10
7   3  7  11
8   0  4   8
9   1  5   9
10  2  6  10
11  3  7  11

In [111]:
pd.concat([df1, df2, df3], axis = 1)

      A    B     C    A    B     C    A    B     C
0   0.0  4.0   8.0  NaN  NaN   NaN  NaN  NaN   NaN
1   1.0  5.0   9.0  NaN  NaN   NaN  NaN  NaN   NaN
2   2.0  6.0  10.0  NaN  NaN   NaN  NaN  NaN   NaN
3   3.0  7.0  11.0  NaN  NaN   NaN  NaN  NaN   NaN
4   NaN  NaN   NaN  0.0  4.0   8.0  NaN  NaN   NaN
5   NaN  NaN   NaN  1.0  5.0   9.0  NaN  NaN   NaN
6   NaN  NaN   NaN  2.0  6.0  10.0  NaN  NaN   NaN
7   NaN  NaN   NaN  3.0  7.0  11.0  NaN  NaN   NaN
8   NaN  NaN   NaN  NaN  NaN   NaN  0.0  4.0   8.0
9   NaN  NaN   NaN  NaN  NaN   NaN  1.0  5.0   9.0
10  NaN  NaN   NaN  NaN  NaN   NaN  2.0  6.0  10.0
11  NaN  NaN   NaN  NaN  NaN   NaN  3.0  7.0  11.0

In [103]:
pd.merge(df1, df2)

   A  B   C
0  0  4   8
1  1  5   9
2  2  6  10
3  3  7  11

### **`df1.join(df2, how = 'inner' or 'outer')`**

In [121]:
left_df = pd.DataFrame(
    {
        'A': [0, 1, 2, 3],
        'B': [4, 5, 6, 7],
        'C': [8, 9, 10, 11]
    }, index = [0, 1, 2, 3]
)

right_df = pd.DataFrame(
    {
        'D': [0, 1, 2, 3],
        'E': [4, 5, 6, 7],
        'F': [8, 9, 10, 11]
    }, index = [0, 2, 4,5]
)

In [123]:
left_df.join(right_df, how = 'inner')

   A  B   C  D  E  F
0  0  4   8  0  4  8
2  2  6  10  1  5  9

In [125]:
left_df.join(right_df, how = 'outer')

     A    B     C    D    E     F
0  0.0  4.0   8.0  0.0  4.0   8.0
1  1.0  5.0   9.0  NaN  NaN   NaN
2  2.0  6.0  10.0  1.0  5.0   9.0
3  3.0  7.0  11.0  NaN  NaN   NaN
4  NaN  NaN   NaN  2.0  6.0  10.0
5  NaN  NaN   NaN  3.0  7.0  11.0

### **`pd.merge(df1, df2, how = 'inner or left or right', on = [columns])`**

In [142]:
left = pd.DataFrame(
    {
        'A': [0, 1, 2, 3],
        'B': [4, 3, 6, 7],
        'C': [8, 9, 10, 11]
    }, index = [0, 1, 2, 3]
)

right = pd.DataFrame(
    {
        'A': [0, 1, 2, 3],
        'B': [4, 5, 6, 7],
        'F': [8, 9, 10, 11]
    }, index = [0, 1, 2, 3]
)

In [144]:
pd.merge(left, right, how = 'left', on = ['A', 'B'])

   A  B   C     F
0  0  4   8   8.0
1  1  3   9   NaN
2  2  6  10  10.0
3  3  7  11  11.0

## Working with Datetime format

In [148]:
df = pd.DataFrame({
        'date': ['2/10/2000', '1/11/2003', '9/12/2003'],
        'value': [3, 1, 5]
    })
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      object
 1   value   3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [154]:
df['date'] = pd.to_datetime(df['date'])

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    3 non-null      datetime64[ns]
 1   value   3 non-null      int64
dtypes: datetime64[ns](1), int64(1)
memory usage: 180.0 bytes

- **Day first format**

In [161]:
df = pd.DataFrame({
        'date': ['2/10/2000', '1/11/2003', '9/12/2003'],
        'value': [3, 1, 5]
    })
df['date'] = pd.to_datetime(df['date'], dayfirst = True)
df

        date  value
0 2000-10-02      3
1 2003-11-01      1
2 2003-12-09      5

- **Custom Format**

In [181]:
df = pd.DataFrame({
        'date': ['2-10-2000 8:57:33', '1-11-2003 3:45:5', '9-12-2003 13:43:50'],
        'value': [3, 1, 5]
    })
df['date'] = pd.to_datetime(df['date'], format = '%d-%m-%Y %H:%M:%S')
df

                 date  value
0 2000-10-02 08:57:33      3
1 2003-11-01 03:45:05      1
2 2003-12-09 13:43:50      5

- **Handle Parsing Error**

In [203]:
df = pd.DataFrame({
        'date': ['2-10-2000 8:57:33', 'a-11-2003 3:45:5', '9-12-2003 13:43:50'],
        'value': [3, 1, 5]
    })
df['date'] = pd.to_datetime(df['date'], errors = 'coerce')
df

                 date  value
0 2000-02-10 08:57:33      3
1                 NaT      1
2 2003-09-12 13:43:50      5

- **Assemble datetime from multiple columns**

In [206]:
df = pd.DataFrame({
    'day': [1, 3, 12],
    'month': [3, 1, 5],
    'year': [2012, 2000, 1997]
    })
df['date'] = pd.to_datetime(df)
df

   day  month  year       date
0    1      3  2012 2012-03-01
1    3      1  2000 2000-01-03
2   12      5  1997 1997-05-12

In [282]:
df = pd.DataFrame({
    'name': ['Andy', 'Dony', 'Sam'],
    'DoB': ['2-10-1997', '29-02-2004', '9-12-2000']
})

df['DoB'] = pd.to_datetime(df['DoB'], dayfirst = True)
df['day'] = df['DoB'].dt.day
df['month'] = df['DoB'].dt.month
df['year'] = df['DoB'].dt.year
df['week_of_year'] = df['DoB'].dt.isocalendar().week
df['day_of_week'] = df['DoB'].dt.dayofweek
df['is_leap_year'] = df['DoB'].dt.is_leap_year

In [284]:
df

   name        DoB  day  month  year  week_of_year  day_of_week  is_leap_year
0  Andy 1997-10-02    2     10  1997            40            3         False
1  Dony 2004-02-29   29      2  2004             9            6          True
2   Sam 2000-12-09    9     12  2000            49            5          True

In [286]:
dw = {
    0: 'Monday',
    1: 'Tuesday',
    2: 'Wednesday',
    3: 'Thursday',
    4: 'Friday',
    5: 'Saturday',
    6: 'Sunday'
}

In [288]:
df['day_of_week'] = df['DoB'].dt.dayofweek.map(dw)
df

   name        DoB  day  month  year  week_of_year day_of_week  is_leap_year
0  Andy 1997-10-02    2     10  1997            40    Thursday         False
1  Dony 2004-02-29   29      2  2004             9      Sunday          True
2   Sam 2000-12-09    9     12  2000            49    Saturday          True

In [290]:
today = pd.to_datetime('today')
df['age'] = today.year - df['year'] 
df

,name,DoB,day,month,year,week_of_year,day_of_week,is_leap_year,age
0,Andy,1997-10-02,2,10,1997,40,Thursday,False,28
1,Dony,2004-02-29,29,2,2004,9,Sunday,True,21
2,Sam,2000-12-09,9,12,2000,49,Saturday,True,25

In [292]:
# Haven't had birthday
b_md = df['DoB'].apply(lambda x: (x.month, x.day))
no_birthday = b_md > (today.month, today.day) 
df['age'] = df['age'] - no_birthday
df

,name,DoB,day,month,year,week_of_year,day_of_week,is_leap_year,age
0,Andy,1997-10-02,2,10,1997,40,Thursday,False,27
1,Dony,2004-02-29,29,2,2004,9,Sunday,True,21
2,Sam,2000-12-09,9,12,2000,49,Saturday,True,24

### Working with File Formats
- JSON

In [4]:
import json

data = {
    "president": {
        "name": "Zaphod Beeblebrox",
        "species": "Betelgeusian"
    }
}

# Writing json files

with open('data_file.json', 'w') as write_file:
    json.dump(data, write_file)

# Reading json files

with open('data_file.json', 'r') as read_file:
    data = json.load(read_file)

In [6]:
type(data)

dict

In [14]:
# Reading json as dataframes in pandas

import pandas as pd

data = '''{"index_0": {"Courses": "Pandas", "Discount": "1200"}, 
"index_1": {"Courses": "Hadoop", "Discount": "1000"}
}'''

df = pd.read_json(data, orient = 'index')
print(df)

        Courses  Discount
index_0  Pandas      1200
index_1  Hadoop      1000

C:\Users\user\AppData\Local\Temp\ipykernel_4564\1787700973.py:9: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  df = pd.read_json(data, orient = 'index')

In [16]:
# Convert dict to df

data = {"index_0": {"Courses": "Pandas", "Discount": "1200"}, 
"index_1": {"Courses": "Hadoop", "Discount": "1000"}
}

df_ = pd.DataFrame.from_dict(data, orient = 'index')
print(df_)

        Courses Discount
index_0  Pandas     1200
index_1  Hadoop     1000

- **CSV**

In [26]:
# Reading a csv file

df_1 = pd.read_csv('hrdata.csv', index_col = 'Name', parse_dates = ['Hire Date'])
print(df_1)

                Hire Date   Salary  Sick Days remaining
Name
Graham Chapman 2014-03-15  50000.0                   10
John Cleese    2015-06-01  65000.0                    8
Eric Idle      2014-05-12  45000.0                   10
Terry Jones    2013-11-01  70000.0                    3
Terry Gilliam  2014-08-12  48000.0                    7
Michael Palin  2013-05-23  66000.0                    8

C:\Users\user\AppData\Local\Temp\ipykernel_4564\1441442743.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_1 = pd.read_csv('hrdata.csv', index_col = 'Name', parse_dates = ['Hire Date'])

In [28]:
df_1.to_csv('hrdata_modified.csv')

- **Excel**

In [33]:
from openpyxl import Workbook

workbook = Workbook()
sheet = workbook.active

sheet['A1'] = 'hello'
sheet['B1'] = 'world'

workbook.save(filename = 'hello_world.xlsx')

In [38]:
# Reading an excel file

from openpyxl import load_workbook

workbook = load_workbook(filename = 'sample-xlsx-file.xlsx')
workbook.sheetnames

['Employee', 'Department']

In [40]:
['Sheet 1']

['Sheet 1']

In [48]:
sheet = workbook.active
sheet

In [50]:
sheet.title

'Employee'

In [52]:
sheet['A1']

In [54]:
sheet['A1'].value

'Name'

In [62]:
sheet.cell(row = 1, column = 4).value

'Salary'

In [70]:
sheet['A1:C3']

((<Cell 'Employee'.A1>, <Cell 'Employee'.B1>, <Cell 'Employee'.C1>),
 (<Cell 'Employee'.A2>, <Cell 'Employee'.B2>, <Cell 'Employee'.C2>),
 (<Cell 'Employee'.A3>, <Cell 'Employee'.B3>, <Cell 'Employee'.C3>))

In [72]:
for row in sheet.iter_rows(values_only = True):
    print(row)

('Name', 'Email', 'Date Of Birth', 'Salary', 'Department')
('Rajeev Singh', 'rajeev@example.com', datetime.datetime(1992, 7, 21, 0, 0), 1500000.0, 'Software Engineering')
('John Doe', 'john@example.com', datetime.datetime(1965, 1, 13, 0, 0), 1300000.0, 'Sales')
('Jack Sparrow', 'jack@example.com', datetime.datetime(1986, 12, 19, 0, 0), 1000000.0, 'HR')
('Steven Cook', 'steven@example.com', datetime.datetime(1994, 5, 4, 0, 0), 1200000.0, 'Marketing')

In [74]:
df_2 = pd.read_excel('sample-xlsx-file.xlsx')
print(df_2)

           Name               Email Date Of Birth   Salary  \
0  Rajeev Singh  rajeev@example.com    1992-07-21  1500000
1      John Doe    john@example.com    1965-01-13  1300000
2  Jack Sparrow    jack@example.com    1986-12-19  1000000
3   Steven Cook  steven@example.com    1994-05-04  1200000

             Department
0  Software Engineering
1                 Sales
2                    HR
3             Marketing

In [76]:
df_2.to_excel('sample-xlsx-modified.xlsx')

- **avro**

In [79]:
pip install avro-python3

Collecting avro-python3
  Downloading avro-python3-1.10.2.tar.gz (38 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: avro-python3
  Building wheel for avro-python3 (setup.py): started
  Building wheel for avro-python3 (setup.py): finished with status 'done'
  Created wheel for avro-python3: filename=avro_python3-1.10.2-py3-none-any.whl size=44036 sha256=a830186465f6a7289e172d7bd75a7833fe62114a08d81d7a9efe7a79c4a57ea7
  Stored in directory: c:\users\user\appdata\local\pip\cache\wheels\df\82\f4\b7126d86d6a404dd59a822fad5f169000deee5f61f7c88580c
Successfully built avro-python3
Installing collected packages: avro-python3
Successfully installed avro-python3-1.10.2
Note: you may need to restart the kernel to use updated packages.

In [85]:
import copy
import json
import avro
from avro.datafile import DataFileWriter, DataFileReader
from avro.io import DatumWriter, DatumReader

schema = {
    'name': 'avro.example.user',
    'type': 'record',
    'fields': [
        {'name': 'name', 'type': 'string'},
        {'name': 'age', 'type' : 'int'}
    ]
}

schema_parsed = avro.schema.Parse(json.dumps(schema))

In [89]:
# Write data to avro file

with open('users.avro', 'wb') as f:
    writer = DataFileWriter(f, DatumWriter(), schema_parsed)
    writer.append({'name': 'Sam', 'age': 32})
    writer.append({'name': 'Sofia', 'age': 33})
    writer.close()

In [91]:
# Read data from avro file

with open('users.avro', 'rb') as f:
    reader = DataFileReader(f, DatumReader())
    metadata = copy.deepcopy(reader.meta)
    parsed_from_file = json.loads(metadata['avro.schema'])
    users = [user for user in reader]
    reader.close()